name: Check PR

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT_FILE: Example/RFIBANHelper.xcodeproj
  PROJECT_SCHEME: RFIBANHelper

jobs:  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.head_ref }}

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run Tests
      run: swift build && swift test

    - name: Perform Cocoapod lib lint validation
      run: make install && make validate
