name: Check PR

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT_FILE: Example/RFIBANHelper.xcodeproj
  PROJECT_SCHEME: RFIBANHelper

jobs:  
  build:

    runs-on: macos-latest

    strategy:
      matrix: 
        xcode:
          - destination: platform=iOS Simulator,OS=latest,name=iPhone 11
            version : latest-stable
          - destination: platform=iOS Simulator,OS=14.4,name=iPhone 11
            version: 12.4
          - destination: platform=iOS Simulator,OS=13.7,name=iPhone 11
            version: 11.7
          - destination: platform=iOS Simulator,OS=12.4,name=iPhone 7
            version: 10.3
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode.version }}

    - name: Xcode Test
      uses: devbotsxyz/xcode-test@v1.1.0
      with:
        project: ${{ env.PROJECT_FILE }}
        scheme: ${{ env.PROJECT_SCHEME }}
        configuration: Debug
        destination: ${{ matrix.xcode.destination }}

    - uses: codecov/codecov-action@v1
      name: Determine code coverage with CodeCov

    - name: Sed new version in Podspec
      run: sed -i "" -e 's|<LIB_VERSION>|1.1.1|g' RFIBAN-Helper.podspec

    - name: Perform Cocoapod lib lint validation
      run: make validate
